export type Project = { slug: string; name: string; fullName: string; category: string; shortDescription: string; overview: string; image: string; imageAlt: string; technologies: string[]; capabilities: string[] };
export const projects: Project[] = [
  { slug: "mira", name: "M.I.R.A.", fullName: "Monitoramento Integrado de Reservatórios e Ajustes", category: "Sistema Web Empresarial / Full Stack", shortDescription: "Monitoramento, conciliação e análise operacional em uma plataforma multiunidade.", overview: "Uma aplicação empresarial para organizar medições físicas, conversões volumétricas, históricos e análises operacionais com controle de acesso.", image: "/images/projects/mira-reservatorios-demo.png", imageAlt: "Painel demonstrativo de reservatórios do M.I.R.A.", technologies: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL", "Prisma"], capabilities: ["Operação multiunidade", "Controle de acesso", "Medições físicas", "Tabelas volumétricas", "Conciliação", "Históricos", "Dashboards e gráficos"] },
  { slug: "recebe", name: "R.E.C.E.B.E.", fullName: "Registro Eletrônico de Controle de Entregas, Bens e Evidências", category: "Sistema Web/Mobile personalizado", shortDescription: "Registro e acompanhamento de recebimentos com uma experiência direta em campo.", overview: "Uma solução responsiva criada para simplificar registros administrativos, centralizar evidências e facilitar o acompanhamento entre campo e gestão.", image: "/images/projects/recebe-mobile-demo.png", imageAlt: "Tela mobile demonstrativa do R.E.C.E.B.E.", technologies: ["Web responsiva", "Experiência mobile", "Fluxos administrativos"], capabilities: ["Registro em campo", "Recebimentos fiscais", "Acompanhamento de aprovações", "Organização por lotes", "Relatórios"] },
  { slug: "prisma", name: "P.R.I.S.M.A.", fullName: "Organização Inteligente de Documentos", category: "Automação e processamento de documentos", shortDescription: "Processamento, conferência e organização de documentos em rotinas guiadas.", overview: "Uma ferramenta focada em reduzir o trabalho manual na organização documental, conduzindo o usuário por rotinas específicas de processamento e conferência.", image: "/images/projects/prisma-home.jpeg", imageAlt: "Tela inicial do P.R.I.S.M.A.", technologies: ["Processamento de documentos", "Aplicativo Windows", "Automação"], capabilities: ["Recibos de salários", "Adiantamentos salariais", "Conferência antes do download", "Organização automatizada"] },
  { slug: "isa", name: "I.S.A.", fullName: "Inteligência e Automação de Processos", category: "RPA / Automação empresarial", shortDescription: "Rotinas programadas para coleta, processamento e geração de relatórios.", overview: "Um conjunto de competências e soluções voltado à automação de navegador, leitura de documentos, tratamento de dados e criação de históricos e relatórios.", image: "/images/projects/analise-relatorios.jpeg", imageAlt: "Painel para análise de relatórios tabelados", technologies: ["Python", "Playwright", "OCR", "Tesseract", "OpenCV", "Pandas", "OpenPyXL", "PDF"], capabilities: ["Automação de navegador", "Coleta de dados", "Processamento de arquivos", "Históricos", "Relatórios automáticos", "Rotinas programadas"] },
  { slug: "caixa-banhos", name: "Controle de Caixa", fullName: "Registro de caixa para sistema de banhos automatizados", category: "Sistema Web Operacional", shortDescription: "Registro de recebimentos, depósitos e relatórios para uma operação de banhos automatizados.", overview: "Uma interface web para apoiar o fechamento diário, organizar movimentações de caixa e consolidar relatórios da operação.", image: "/images/projects/sistema-caixa-banhos-demo.png", imageAlt: "Sistema demonstrativo de registro de caixa", technologies: ["Sistema web", "Interface responsiva", "Relatórios"], capabilities: ["Registro de banhos", "Controle de depósitos", "Histórico de movimentações", "Consolidação de relatórios"] },
  { slug: "analise-relatorios", name: "Análise de Relatórios", fullName: "Análise e apresentação de relatórios tabelados", category: "Sistema Web de Dados", shortDescription: "Importação e apresentação detalhada de relatórios tabelados básicos.", overview: "Uma ferramenta web para transformar relatórios tabulares em uma visão gerencial clara, com processamento local e exploração das informações.", image: "/images/projects/analise-relatorios.jpeg", imageAlt: "Painel vazio de análise de vendas", technologies: ["Sistema web", "Processamento local", "Visualização de dados"], capabilities: ["Importação de CSV", "Resumo do período", "Agrupamento de informações", "Apresentação de indicadores"] },
];
